# Generated by Django 4.2.6 on 2023-10-10 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0020_test_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='score',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
