# Generated by Django 4.2.6 on 2023-10-10 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0024_rename_test_question_test_belongs_to_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='test_belongs_to',
            new_name='test',
        ),
        migrations.RemoveField(
            model_name='test',
            name='current_question',
        ),
        migrations.AlterField(
            model_name='test',
            name='start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
