# Generated by Django 4.2.6 on 2023-10-08 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0018_question_choice'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Choice',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
    ]
