# Generated by Django 4.2.6 on 2023-10-10 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0021_test_score'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='test',
            name='score',
        ),
    ]
